CLUSTER_LOG_TTL_HOURS: 24
ENCRYPTION_KEY: kJf2wgojO4AUSszv+fXg8dYi/K8wlQ3rwpXP7ZgbYaM=
GIN_MODE: debug
INVITE_CODE: "735806"
JWT_SECRET: mGHaBcNM6xUndEZoXQcT2twp3TQrIZ8EMNSNbhN5v6Q=
TOKEN_REFRESH_MAX_AGE_DAYS: 7
MONGODB:
  HOST: localhost
  NAME: kubeorch
  PORT: 27017
PORT: 3000
