apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace | default "default" }}
  labels:
    app: {{ .Name }}
    managed-by: kubeorch
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  {{- if .StorageClassName }}
  storageClassName: {{ .StorageClassName }}
  {{- end }}
  accessModes:
  {{- range .AccessModes }}
  - {{ . }}
  {{- end }}
  {{- if .VolumeMode }}
  volumeMode: {{ .VolumeMode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Storage }}
