package services

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/KubeOrch/core/models"
)

// NixpacksProvider represents a detected language/framework provider
type NixpacksProvider string

const (
	NixpacksProviderNode   NixpacksProvider = "node"
	NixpacksProviderPython NixpacksProvider = "python"
	NixpacksProviderGo     NixpacksProvider = "go"
	NixpacksProviderRust   NixpacksProvider = "rust"
	NixpacksProviderRuby   NixpacksProvider = "ruby"
	NixpacksProviderPHP    NixpacksProvider = "php"
	NixpacksProviderJava   NixpacksProvider = "java"
	NixpacksProviderDotnet NixpacksProvider = "dotnet"
	NixpacksProviderStatic NixpacksProvider = "staticfile"
)

// NixpacksPlan represents the build plan generated by Nixpacks
type NixpacksPlan struct {
	Providers []string          `json:"providers"`
	BuildCmd  string            `json:"buildCmd,omitempty"`
	StartCmd  string            `json:"startCmd,omitempty"`
	Variables map[string]string `json:"variables,omitempty"`
	Phases    map[string]Phase  `json:"phases,omitempty"`
}

// Phase represents a build phase in Nixpacks
type Phase struct {
	DependsOn  []string `json:"dependsOn,omitempty"`
	NixPkgs    []string `json:"nixPkgs,omitempty"`
	AptPkgs    []string `json:"aptPkgs,omitempty"`
	CmdsPrefix []string `json:"cmdsPrefix,omitempty"`
	Cmds       []string `json:"cmds,omitempty"`
}

// NixpacksResult contains the analysis result from Nixpacks
type NixpacksResult struct {
	Provider      NixpacksProvider
	Providers     []string
	BuildCommand  string
	StartCommand  string
	Environment   map[string]string
	DefaultPort   int
	Dockerfile    string
	Plan          *NixpacksPlan
	Warnings      []string
}

// NixpacksService handles Nixpacks-based project detection
type NixpacksService struct {
	nixpacksPath string
	timeout      time.Duration
}

// NewNixpacksService creates a new Nixpacks service
func NewNixpacksService() *NixpacksService {
	// Try to find nixpacks in PATH
	path, _ := exec.LookPath("nixpacks")
	if path == "" {
		// Common installation locations
		locations := []string{
			"/usr/local/bin/nixpacks",
			"/usr/bin/nixpacks",
			"~/.cargo/bin/nixpacks",
		}
		for _, loc := range locations {
			if loc[0] == '~' {
				home, _ := os.UserHomeDir()
				loc = filepath.Join(home, loc[2:])
			}
			if _, err := os.Stat(loc); err == nil {
				path = loc
				break
			}
		}
	}

	return &NixpacksService{
		nixpacksPath: path,
		timeout:      60 * time.Second,
	}
}

// IsAvailable checks if Nixpacks is installed and available
func (s *NixpacksService) IsAvailable() bool {
	return s.nixpacksPath != ""
}

// Detect analyzes a directory and detects the project type
func (s *NixpacksService) Detect(ctx context.Context, repoPath string) (*NixpacksResult, error) {
	if !s.IsAvailable() {
		// Fall back to manual detection
		return s.manualDetect(repoPath)
	}

	// Run nixpacks plan to get the build plan
	ctx, cancel := context.WithTimeout(ctx, s.timeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, s.nixpacksPath, "plan", "--format", "json", repoPath)
	output, err := cmd.Output()
	if err != nil {
		// If nixpacks fails, fall back to manual detection
		return s.manualDetect(repoPath)
	}

	var plan NixpacksPlan
	if err := json.Unmarshal(output, &plan); err != nil {
		return nil, fmt.Errorf("failed to parse nixpacks plan: %w", err)
	}

	result := &NixpacksResult{
		Plan:        &plan,
		Providers:   plan.Providers,
		BuildCommand: plan.BuildCmd,
		StartCommand: plan.StartCmd,
		Environment: plan.Variables,
	}

	if len(plan.Providers) > 0 {
		result.Provider = NixpacksProvider(plan.Providers[0])
	} else if metadata, ok := plan.Variables["NIXPACKS_METADATA"]; ok && metadata != "" {
		// For SPAs and some projects, providers may be empty but NIXPACKS_METADATA is set
		result.Provider = NixpacksProvider(metadata)
		result.Providers = []string{metadata}
	}

	// Determine default port based on provider
	result.DefaultPort = s.getDefaultPort(result.Provider)

	return result, nil
}

// GenerateDockerfile generates a Dockerfile using Nixpacks
// outputDir is where nixpacks will create the .nixpacks/ folder containing the Dockerfile and supporting files
// Returns the path to the generated Dockerfile
func (s *NixpacksService) GenerateDockerfile(ctx context.Context, repoPath string, outputDir string) (string, error) {
	if !s.IsAvailable() {
		return "", fmt.Errorf("nixpacks is not installed")
	}

	ctx, cancel := context.WithTimeout(ctx, s.timeout)
	defer cancel()

	// If outputDir is empty, use repoPath as the output directory
	if outputDir == "" {
		outputDir = repoPath
	}

	// nixpacks build --out outputs to <dir>/.nixpacks/Dockerfile along with supporting files
	// The Dockerfile references these files (e.g., COPY .nixpacks/assets /assets/)
	// So we need to output directly to the build context directory
	dockerfilePath := filepath.Join(outputDir, ".nixpacks", "Dockerfile")

	cmd := exec.CommandContext(ctx, s.nixpacksPath, "build", "--out", outputDir, repoPath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("failed to generate Dockerfile: %w - %s", err, string(output))
	}

	// Verify the Dockerfile was created
	if _, err := os.Stat(dockerfilePath); err != nil {
		return "", fmt.Errorf("Dockerfile not found at expected path %s: %w", dockerfilePath, err)
	}

	return dockerfilePath, nil
}

// GenerateFallbackDockerfile generates a basic Dockerfile based on detected project type
// This is used when Nixpacks CLI is not available
func (s *NixpacksService) GenerateFallbackDockerfile(provider NixpacksProvider, result *NixpacksResult) (string, error) {
	var dockerfile string

	switch provider {
	case NixpacksProviderNode:
		dockerfile = s.generateNodeDockerfile(result)
	case NixpacksProviderPython:
		dockerfile = s.generatePythonDockerfile(result)
	case NixpacksProviderGo:
		dockerfile = s.generateGoDockerfile(result)
	case NixpacksProviderRust:
		dockerfile = s.generateRustDockerfile(result)
	case NixpacksProviderStatic:
		dockerfile = s.generateStaticDockerfile(result)
	default:
		return "", fmt.Errorf("no fallback Dockerfile template for provider: %s", provider)
	}

	return dockerfile, nil
}

func (s *NixpacksService) generateNodeDockerfile(result *NixpacksResult) string {
	// Determine package manager from build command
	packageManager := "npm"
	installCmd := "npm install"
	if strings.Contains(result.BuildCommand, "yarn") {
		packageManager = "yarn"
		installCmd = "yarn install"
	} else if strings.Contains(result.BuildCommand, "pnpm") {
		packageManager = "pnpm"
		installCmd = "pnpm install"
	} else if strings.Contains(result.BuildCommand, "bun") {
		packageManager = "bun"
		installCmd = "bun install"
	}

	hasBuild := strings.Contains(result.BuildCommand, "build")
	buildStep := ""
	if hasBuild {
		buildStep = fmt.Sprintf("RUN %s run build\n", packageManager)
	}

	return fmt.Sprintf(`# Auto-generated Dockerfile for Node.js project
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
%s

# Install dependencies
RUN %s

# Copy source
COPY . .

%s
# Production stage
FROM node:20-alpine

WORKDIR /app

# Copy built application
COPY --from=builder /app ./

# Set environment
ENV NODE_ENV=production
ENV PORT=%d

EXPOSE %d

CMD ["%s"]
`, func() string {
		if packageManager == "yarn" {
			return "COPY yarn.lock* ./"
		} else if packageManager == "pnpm" {
			return "COPY pnpm-lock.yaml* ./"
		} else if packageManager == "bun" {
			return "COPY bun.lockb* ./"
		}
		return ""
	}(), installCmd, buildStep, result.DefaultPort, result.DefaultPort, result.StartCommand)
}

func (s *NixpacksService) generatePythonDockerfile(result *NixpacksResult) string {
	return fmt.Sprintf(`# Auto-generated Dockerfile for Python project
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || true

COPY pyproject.toml* ./
RUN pip install . 2>/dev/null || true

# Copy source
COPY . .

ENV PORT=%d

EXPOSE %d

CMD ["%s"]
`, result.DefaultPort, result.DefaultPort, result.StartCommand)
}

func (s *NixpacksService) generateGoDockerfile(result *NixpacksResult) string {
	return fmt.Sprintf(`# Auto-generated Dockerfile for Go project
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum* ./
RUN go mod download

# Copy source
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/main .

# Production stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main ./main

ENV PORT=%d

EXPOSE %d

CMD ["./main"]
`, result.DefaultPort, result.DefaultPort)
}

func (s *NixpacksService) generateRustDockerfile(result *NixpacksResult) string {
	return fmt.Sprintf(`# Auto-generated Dockerfile for Rust project
FROM rust:1.75-alpine AS builder

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache musl-dev

# Copy manifests
COPY Cargo.toml Cargo.lock* ./

# Copy source
COPY src ./src

# Build
RUN cargo build --release

# Production stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/target/release/* ./

ENV PORT=%d

EXPOSE %d

CMD ["./app"]
`, result.DefaultPort, result.DefaultPort)
}

func (s *NixpacksService) generateStaticDockerfile(result *NixpacksResult) string {
	return `# Auto-generated Dockerfile for static files
FROM nginx:alpine

COPY . /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
`
}

// manualDetect performs manual project detection without Nixpacks
func (s *NixpacksService) manualDetect(repoPath string) (*NixpacksResult, error) {
	result := &NixpacksResult{
		Environment: make(map[string]string),
		Warnings:    []string{},
	}

	// Check for common project files
	detectors := []struct {
		files    []string
		provider NixpacksProvider
		build    string
		start    string
		port     int
	}{
		// Node.js
		{
			files:    []string{"package.json"},
			provider: NixpacksProviderNode,
			build:    "npm install && npm run build",
			start:    "npm start",
			port:     3000,
		},
		// Python
		{
			files:    []string{"requirements.txt", "pyproject.toml", "setup.py", "Pipfile"},
			provider: NixpacksProviderPython,
			build:    "pip install -r requirements.txt",
			start:    "python app.py",
			port:     8000,
		},
		// Go
		{
			files:    []string{"go.mod"},
			provider: NixpacksProviderGo,
			build:    "go build -o app",
			start:    "./app",
			port:     8080,
		},
		// Rust
		{
			files:    []string{"Cargo.toml"},
			provider: NixpacksProviderRust,
			build:    "cargo build --release",
			start:    "./target/release/app",
			port:     8080,
		},
		// Ruby
		{
			files:    []string{"Gemfile"},
			provider: NixpacksProviderRuby,
			build:    "bundle install",
			start:    "bundle exec ruby app.rb",
			port:     3000,
		},
		// PHP
		{
			files:    []string{"composer.json", "index.php"},
			provider: NixpacksProviderPHP,
			build:    "composer install",
			start:    "php -S 0.0.0.0:8080",
			port:     8080,
		},
		// Java (Maven)
		{
			files:    []string{"pom.xml"},
			provider: NixpacksProviderJava,
			build:    "mvn package",
			start:    "java -jar target/*.jar",
			port:     8080,
		},
		// Java (Gradle)
		{
			files:    []string{"build.gradle", "build.gradle.kts"},
			provider: NixpacksProviderJava,
			build:    "./gradlew build",
			start:    "java -jar build/libs/*.jar",
			port:     8080,
		},
		// .NET
		{
			files:    []string{"*.csproj", "*.fsproj"},
			provider: NixpacksProviderDotnet,
			build:    "dotnet publish -c Release",
			start:    "dotnet run",
			port:     5000,
		},
		// Static files
		{
			files:    []string{"index.html"},
			provider: NixpacksProviderStatic,
			build:    "",
			start:    "",
			port:     80,
		},
	}

	for _, detector := range detectors {
		for _, file := range detector.files {
			// Handle glob patterns
			if strings.Contains(file, "*") {
				matches, _ := filepath.Glob(filepath.Join(repoPath, file))
				if len(matches) > 0 {
					result.Provider = detector.provider
					result.Providers = []string{string(detector.provider)}
					result.BuildCommand = detector.build
					result.StartCommand = detector.start
					result.DefaultPort = detector.port
					result.Warnings = append(result.Warnings, "Using manual detection (nixpacks not available)")
					return result, nil
				}
			} else {
				filePath := filepath.Join(repoPath, file)
				if _, err := os.Stat(filePath); err == nil {
					result.Provider = detector.provider
					result.Providers = []string{string(detector.provider)}
					result.BuildCommand = detector.build
					result.StartCommand = detector.start
					result.DefaultPort = detector.port

					// Read package.json for Node.js to get better start command
					if detector.provider == NixpacksProviderNode {
						s.enrichNodeDetection(repoPath, result)
					}

					result.Warnings = append(result.Warnings, "Using manual detection (nixpacks not available)")
					return result, nil
				}
			}
		}
	}

	return nil, fmt.Errorf("unable to detect project type")
}

// enrichNodeDetection reads package.json to get more accurate build/start commands
func (s *NixpacksService) enrichNodeDetection(repoPath string, result *NixpacksResult) {
	packageJSONPath := filepath.Join(repoPath, "package.json")
	content, err := os.ReadFile(packageJSONPath)
	if err != nil {
		return
	}

	var pkg struct {
		Scripts map[string]string `json:"scripts"`
		Main    string            `json:"main"`
	}
	if err := json.Unmarshal(content, &pkg); err != nil {
		return
	}

	// Determine package manager
	packageManager := "npm"
	if _, err := os.Stat(filepath.Join(repoPath, "yarn.lock")); err == nil {
		packageManager = "yarn"
	} else if _, err := os.Stat(filepath.Join(repoPath, "pnpm-lock.yaml")); err == nil {
		packageManager = "pnpm"
	} else if _, err := os.Stat(filepath.Join(repoPath, "bun.lockb")); err == nil {
		packageManager = "bun"
	}

	// Set build command
	if _, ok := pkg.Scripts["build"]; ok {
		result.BuildCommand = fmt.Sprintf("%s install && %s run build", packageManager, packageManager)
	} else {
		result.BuildCommand = fmt.Sprintf("%s install", packageManager)
	}

	// Set start command
	if _, ok := pkg.Scripts["start"]; ok {
		result.StartCommand = fmt.Sprintf("%s start", packageManager)
	} else if pkg.Main != "" {
		result.StartCommand = fmt.Sprintf("node %s", pkg.Main)
	} else {
		result.StartCommand = "node index.js"
	}

	// Check for common frameworks
	if _, ok := pkg.Scripts["dev"]; ok {
		// Likely a dev server framework like Next.js, Vite, etc.
		result.DefaultPort = 3000
	}
}

// getDefaultPort returns the default port for a provider
func (s *NixpacksService) getDefaultPort(provider NixpacksProvider) int {
	switch provider {
	case NixpacksProviderNode:
		return 3000
	case NixpacksProviderPython:
		return 8000
	case NixpacksProviderGo, NixpacksProviderRust, NixpacksProviderJava, NixpacksProviderPHP:
		return 8080
	case NixpacksProviderRuby:
		return 3000
	case NixpacksProviderDotnet:
		return 5000
	case NixpacksProviderStatic:
		return 80
	default:
		return 8080
	}
}

// ConvertToImportAnalysis converts Nixpacks result to ImportAnalysis
func (s *NixpacksService) ConvertToImportAnalysis(result *NixpacksResult, repoName string) *models.ImportAnalysis {
	// Create a simple service from the Nixpacks detection
	service := models.ImportedService{
		Name:        repoName,
		Image:       fmt.Sprintf("%s:latest", strings.ToLower(repoName)),
		Environment: result.Environment,
		Ports: []models.PortMapping{
			{
				ContainerPort: result.DefaultPort,
				Protocol:      "TCP",
			},
		},
		Replicas: 1,
	}

	if result.BuildCommand != "" {
		service.Build = &models.BuildConfig{
			Context: ".",
		}
	}

	analysis := &models.ImportAnalysis{
		DetectedType: fmt.Sprintf("nixpacks-%s", result.Provider),
		Services:     []models.ImportedService{service},
		Warnings:     result.Warnings,
	}

	// Add warning about needing to build the image
	if result.BuildCommand != "" {
		analysis.Warnings = append(analysis.Warnings,
			fmt.Sprintf("This project uses %s. You'll need to build a container image before deploying.", result.Provider),
			fmt.Sprintf("Build command: %s", result.BuildCommand),
			fmt.Sprintf("Start command: %s", result.StartCommand),
		)
	}

	return analysis
}
