apiVersion: v1
kind: Secret
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace | default "default" }}
  labels:
    app: {{ .Name }}
    managed-by: kubeorch
    {{- range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
type: {{ .SecretType | default "Opaque" }}
data:
  {{- range $key, $value := .Data }}
  {{ $key }}: {{ $value | base64encode }}
  {{- end }}
